In [ ]:
!pip install google-api-python-client langdetect

Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (2.194.0)
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 14.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (0.31.2)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.47.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (0.3.1)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.30.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (4.2.0)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.74.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.27.2)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (4.9.1)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.3.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2026.2.25)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=581604f2bc3ecf9315765cf07e4e52c437c6944452f0b949925385310799f49d
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

### Real world dataset
This is a small notebook that fetches comments on a popular mr. beast video and uses the roberta model to detect how many of them are AI-generated

In [ ]:
import os, json, time
import googleapiclient.discovery
import googleapiclient.errors
import pandas as pd
from tqdm.notebook import tqdm

path = "/content/drive/MyDrive/ML_project/"
device = "cuda"
API_KEY  = "AIzaSyDelfR1NePM8wdP_O5xts_OLjwNY3TtiOk"
video_id = "DXVHmGoCTco"
save_path = f"{path}/comments_{video_id}.jsonl"

youtube = googleapiclient.discovery.build(
    "youtube", "v3", developerKey=API_KEY, cache_discovery=False
)

In [ ]:
video_resp = youtube.videos().list(part="statistics", id=video_id).execute()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
video_resp

{'kind': 'youtube#videoListResponse',
 'etag': 'y5D2hBbJu8Mkasy1OpR2pa8nKSk',
 'items': [{'kind': 'youtube#video',
   'etag': 'Vz35q9NwVwAM5-UK3u3pUdr7pa4',
   'id': 'DXVHmGoCTco',
   'statistics': {'viewCount': '93212072',
    'likeCount': '2382769',
    'favoriteCount': '0',
    'commentCount': '161667'}}],
 'pageInfo': {'totalResults': 1, 'resultsPerPage': 1}}

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:

def retrieve_comments(video_id):
    page_token = None
    fetched_ids = set()
    with open(save_path, "a") as f:
        while True:
            try:
                resp = youtube.commentThreads().list(
                    part="snippet",
                    videoId=video_id,
                    maxResults=100,
                    order="time",
                    pageToken=page_token,
                ).execute()
            except googleapiclient.errors.HttpError as e:
                print(f"error: {e}")
                break

            items = resp.get("items", [])
            print(f"Fetched {len(fetched_ids)}")
            for item in items:
                comment_id = item["id"]
                if comment_id in fetched_ids:
                    continue

                s = item["snippet"]["topLevelComment"]["snippet"]
                row = {
                    "id": comment_id,
                    "text": s.get("textOriginal", ""),
                    "author": s.get("authorDisplayName", ""),
                    "author_channel": s.get("authorChannelId", {}).get("value", ""),
                    "like_count": s.get("likeCount", 0),
                    "reply_count": item["snippet"].get("totalReplyCount", 0),
                    "published_at": s.get("publishedAt", ""),
                    "updated_at": s.get("updatedAt", ""),
                }
                f.write(json.dumps(row) + "\n")
                fetched_ids.add(comment_id)

            page_token = resp.get("nextPageToken")
            if page_token is None:
                print(f"No more pages. Total fetched: {len(fetched_ids)}")
                break
            if len(fetched_ids) >= 2000:
                break
    return fetched_ids

In [ ]:
fetched_ids = retrieve_comments(video_id)

Fetched 0
Fetched 100
Fetched 200
Fetched 300
Fetched 400
Fetched 500
Fetched 600
Fetched 700
Fetched 800
Fetched 900
Fetched 1000
Fetched 1100
Fetched 1200
Fetched 1300
Fetched 1400
Fetched 1500
Fetched 1600
Fetched 1700
Fetched 1800
Fetched 1900

In [ ]:
from langdetect import detect

df = pd.read_json(save_path, lines=True)
df.head()

,id,text,author,author_channel,like_count,reply_count,published_at,updated_at
0,UgzoTD5YBfsX4xvnclx4AaABAg,Who is your favorite streamer?,@MrBeast,UCX6OQ3DkcsbYNE6H8uQQuVA,62925,1000,2026-04-04 15:57:56+00:00,2026-04-05 19:14:50+00:00
1,Ugyr2xAjIyWZcQ6FQHF4AaABAg,"Say what you will, Rakai is quite talented.",@SametKum-k6g,UCo3crOWKRjEY9Dg7iBejmZA,0,0,2026-04-20 01:44:39+00:00,2026-04-20 01:44:39+00:00
2,Ugw3p7mBQEXyqIzIcfZ4AaABAg,Steak is my fav stremer,@ShylynnHirshon-v9r,UCr6YkW3NLVro2ZiQxkBxFbQ,0,0,2026-04-20 01:44:21+00:00,2026-04-20 01:44:21+00:00
3,Ugy8Q66FKyOzeopP9dd4AaABAg,rakai is an absolute menace☠️,@ItzJay-n5t,UC_WhHVGy2oUCIs25Yfj1ilQ,0,0,2026-04-20 01:43:31+00:00,2026-04-20 01:43:31+00:00
4,UgxtT8oSthfrpw9_iv94AaABAg,day 1000 = 10000000000000000000000000000000000...,@jenalynIhong-i7q,UCl6lmZcjbrgkSmw3b9nrE2w,0,1,2026-04-20 01:42:22+00:00,2026-04-20 01:42:22+00:00

In [ ]:
def detect_language_safe(text):
    try:
        return detect(text)
    except:
        return "error"

# apply language detection to filter out non-English comments
df["language"] = df["text"].apply(lambda x: detect_language_safe(x))
df_en = df[df["language"] == "en"].copy()

In [ ]:
df["language"].value_counts().head(5)

language
en       1047
es        147
error      84
id         79
so         62
Name: count, dtype: int64

# evaluating our models

In [ ]:
import torch
import numpy as np

In [ ]:

from torch.utils.data import Dataset, DataLoader
from transformers import RobertaTokenizerFast, RobertaForSequenceClassification


class TextDataset(Dataset):
    def __init__(self, texts, tokenizer, max_length=128):
        self.encodings = tokenizer(
            list(texts), truncation=True, padding="max_length", max_length=max_length
        )
        # self.labels = list(labels)

    def __len__(self):
        return len(self.encodings["input_ids"])

    def __getitem__(self, idx):
        return {
            "input_ids": torch.tensor(self.encodings["input_ids"][idx]),
            "attention_mask": torch.tensor(self.encodings["attention_mask"][idx]),
            # "labels": torch.tensor(self.labels[idx], dtype=torch.long),
        }


def run_inference(model, dataset, batch_size=64):
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)
    model.eval()
    logits_list, labels_list = [], []
    with torch.no_grad():
        for batch in loader:
            outputs = model(
                input_ids=batch["input_ids"].to(device),
                attention_mask=batch["attention_mask"].to(device),
            )
            logits_list.append(outputs.logits.cpu().numpy())
            # labels_list.append(batch["labels"].numpy())
    return np.concatenate(logits_list)

In [ ]:
from scipy.special import softmax
threshold = 0.9749
tokenizer = RobertaTokenizerFast.from_pretrained(f"{path}/checkpoints/tokenizer")
model_a = RobertaForSequenceClassification.from_pretrained(f"{path}/checkpoints/model_a/config_3")
model_a.to(device)
test_ds_a = TextDataset(df_en["text"], tokenizer)
test_logits = run_inference(model_a, test_ds_a)
test_probs = softmax(test_logits, axis=1)[:, 1]
preds = (test_probs >= threshold).astype(int)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
ai_generated_df = df_en.iloc[preds == 1]
ai_generated_df.head()

,id,text,author,author_channel,like_count,reply_count,published_at,updated_at,language
0,UgzoTD5YBfsX4xvnclx4AaABAg,Who is your favorite streamer?,@MrBeast,UCX6OQ3DkcsbYNE6H8uQQuVA,62925,1000,2026-04-04 15:57:56+00:00,2026-04-05 19:14:50+00:00,en
1,Ugyr2xAjIyWZcQ6FQHF4AaABAg,"Say what you will, Rakai is quite talented.",@SametKum-k6g,UCo3crOWKRjEY9Dg7iBejmZA,0,0,2026-04-20 01:44:39+00:00,2026-04-20 01:44:39+00:00,en
31,Ugzw8jook6LHnKAnZkp4AaABAg,Yall hating on rakai but if I was there Yal wo...,@Samuelstiven123,UCgZTyXSPiyLPfu8r_IhYHww,0,0,2026-04-20 00:35:13+00:00,2026-04-20 00:35:13+00:00,en
53,UgzRKg1XVzuDU0qPUOF4AaABAg,After they reached the point where they only n...,@joshuaw7754,UCwssO9d7NBS0PBvSmQozqXw,0,0,2026-04-19 23:29:32+00:00,2026-04-19 23:49:05+00:00,en
76,UgwMsHpWlzXSJWJupfl4AaABAg,The fact these grown people cant kick a soccer...,@VexrylTTV,UCqdD5c2xkUgN96tX4L8C6Aw,0,0,2026-04-19 22:33:57+00:00,2026-04-19 22:33:57+00:00,en

looking at these comments i don't know if they are actually ai-generated, however, they don't look like they are ai generated!

In [ ]:
non_popular = ai_generated_df[ (ai_generated_df["like_count"] == 0) & ((ai_generated_df["reply_count"] == 0))]

In [ ]:
non_popular

,id,text,author,author_channel,like_count,reply_count,published_at,updated_at,language
1,Ugyr2xAjIyWZcQ6FQHF4AaABAg,"Say what you will, Rakai is quite talented.",@SametKum-k6g,UCo3crOWKRjEY9Dg7iBejmZA,0,0,2026-04-20 01:44:39+00:00,2026-04-20 01:44:39+00:00,en
31,Ugzw8jook6LHnKAnZkp4AaABAg,Yall hating on rakai but if I was there Yal wo...,@Samuelstiven123,UCgZTyXSPiyLPfu8r_IhYHww,0,0,2026-04-20 00:35:13+00:00,2026-04-20 00:35:13+00:00,en
53,UgzRKg1XVzuDU0qPUOF4AaABAg,After they reached the point where they only n...,@joshuaw7754,UCwssO9d7NBS0PBvSmQozqXw,0,0,2026-04-19 23:29:32+00:00,2026-04-19 23:49:05+00:00,en
76,UgwMsHpWlzXSJWJupfl4AaABAg,The fact these grown people cant kick a soccer...,@VexrylTTV,UCqdD5c2xkUgN96tX4L8C6Aw,0,0,2026-04-19 22:33:57+00:00,2026-04-19 22:33:57+00:00,en
96,Ugwx50BB2re0_FihCpR4AaABAg,@MrBeast I know you change people’s lives and ...,@SprunkiBoyOfficial,UC-QZ_dJ3_rG0fg421hj_GLQ,0,0,2026-04-19 21:36:51+00:00,2026-04-19 21:36:51+00:00,en
...,...,...,...,...,...,...,...,...,...
1913,Ugz3CpEl2deqSNdlmIN4AaABAg,Eliminating Rakai is the most satisfying in th...,@Deuce_Crow25,UCiYLdahFigfW00Ti5FdvXng,0,0,2026-04-18 04:37:12+00:00,2026-04-18 04:37:12+00:00,en
1981,UgzkqZAdkQi7aVPfLGF4AaABAg,"“Dear MrBeast,\nI’m begging you from the botto...",@genzoriginal,UCkkFWcatltpxDjjhwp0or8Q,0,0,2026-04-18 03:38:44+00:00,2026-04-18 03:38:44+00:00,en
1982,Ugw014PllO_loDu4fYV4AaABAg,"I love watching these but at the same time, i ...",@joemason285,UC1N_1GwxLwblXwlGSp5Eikw,0,0,2026-04-18 03:38:14+00:00,2026-04-18 03:38:14+00:00,en
1984,Ugw1X1mCyjzrNcXIcKZ4AaABAg,"Rakai is so annoying , he needs to act more hi...",@danajatomlinson6615,UCxlP3qB1xJCQfBQrKp0BZIA,0,0,2026-04-18 03:38:05+00:00,2026-04-18 03:38:05+00:00,en
1992,UgzFpmc9gI7m3Y_NlX54AaABAg,Thank you for sharing this. I learned so much ...,@BeatMover-2026,UCyDoKF8Imz7yqKujC-ir_FQ,0,0,2026-04-18 03:26:11+00:00,2026-04-18 03:26:11+00:00,en

In [ ]:
for item in non_popular["text"]:
    print(item)

Say what you will, Rakai is quite talented.
Yall hating on rakai but if I was there Yal woulda hate me. 😭😭💯
After they reached the point where they only needed one point, they should have spread out.
Also, very frustrating at the last stage where they all act like they don’t want to hit anyone. They goal of a competition is to compete
The fact these grown people cant kick a soccer ball, is CRAZY
@MrBeast I know you change people’s lives and make dreams real. 🙏
Please help me too — my channel @SprunkiBoyOfficial got demonetized unfairly.
I didn’t break any rules. This is my only income. Please notice me ❤
The amount of DISRESPECT from Rakai is just crazy to me, thats what happens when a kid builds an ego and its unfortunately supported online. Dude just shut up and be respectful fr.
Rakai should have won.
Please, can you give me 1000 dollars? I'm a subscriber and a fan from Türkiye TGeywy3GYj3JiEUCHGzE7dw9mk6YRjFZiP
For the next streamer event add @mishifu please
I love you video because you do so good my number is 120 Everett
38:09 The ball goes beyond the camera, this is a post.
Poor Karai, for being so arrogant, karma caught up with her.   😂
Sad, a bunch of young men throw like a bunch of old women because they sit in front of a computer all day instead of going outside!
"Xxxtentacion watching ski tryna win for him
Was I the only one rooting for rakai?
Hey mrbeast I’m starting my YouTube channel since à young age I wanted to start a channel and to become big you inspired me as a young age my parents told me I wouldn’t be anything in life so I have to show them I can be something so your video counting to 100,000 was great as why I’m recreating this but how ever counting to a million. I will show my parents I will make it and I won’t quit till I die tell me if yall wanna see this as a series counting to 1M!
Can I be in one of your vids?
I’m so happy Mrbeast didn’t put rakai on the thumbnail, would’ve ruined numbers.
Hey MrBeast, I just wanted to share a small request. I genuinely love your videos and the creativity and effort you put into them, they’re honestly some of my favorite content to watch.

One thing I’ve noticed is that I enjoy your videos the most when the games feel completely fair and everyone is playing honestly. Those moments make the videos more exciting and satisfying to watch. When there’s cheating involved, it kind of takes away from that feeling for me, and I don’t enjoy it as much.

I’m not sure if others feel the same way, but I wanted to share this respectfully. This is only coming from a place of appreciation, I truly admire what you do and everything you’ve built. Just a humble request, nothing but love 🙌
I watch your every video, I watch your every video since 2019, I really want to participate in one of your videos,, I am a citizen of Bangladesh, I am from a very poor family, can you let me participate in a video, Jamie?😭🙏
On behalf of 100 million people of Vietnam, send greetings to Mr. Beast and the team. We invite Mr. Beast and his team to visit my country! I pledge to have at least 50 million subscribers to Mr Beast channel! And I will join Mr Beast channel membership forever if you come over and host the game in my country! Welcome Mr Beast!!!❤❤❤🎉🎉🎉🎉
Ts is actually so unwatchable there's no way people actually watch streamers.
@MrBeast can u put Joe bartalozzi in a video pleasseee 🙏🙏
Hi jimi uncle what you give me 1000 $ for buying laptop for starting game development studio i returned in 1 year
Rakai, you cheat, we want justice for Abraham.
There's no one from Türkiye, please invite me to the competition too.
MrBeast, from the bottom of my heart, I ask for your help. My dream is to grow on my social media, gain followers, and keep moving forward, striving to become someone in life. This means a lot to me—it’s a goal I want to achieve with all my effort.
God bless you always, and thank you for listening.
Ngl why didnt they go on their tippy toes for the shape game to ensure everyone is in the shape?
I don't understand why nobody wants to shoot when the goalkeeper is so bad.
How did everyone i voted for get out ._. I voted for Alex then Andrea then the fortnite pros then Nike then Tyler and also Jason and Rubius but atleast Raikai didnt win thats all that matters lol L bro sucks
I think MR. Beast should invite Marie in more challenges....
MrBeast, there seemed to be too much cheating in this video (car timing, Abraham, and the 3 vs Rubius situation).
Please try to keep things fair in future videos. Also, it would be great if participants were chosen more carefully. There were some mentally unstable = toxic environement.

Otherwise, I enjoyed the video—thanks for making it!
Dear MrBeast, I watch all of your new videos completely and have been following you for a long time. I am a very big fan of yours. I am in great need right now. Please, I urgently need one thousand dollars. Your help would mean a lot to me. Kindly read my message and please reply. I truly need help right now. Thank you.
"Win for me, Andrea!"
She's out next round.
Before you hate on any streamer, remember they are professional attention seekers. Sometimes you have to be odd to get people's attention and that's exactly what they are doing. I think Rakai is just doing what gets him the attention he needs for his career.
There is no Ivan Zolo. It doesn't count.
Mr. Beast hello you are best youtuber in live i  is your fans in 2022 bro i from indonesia plis give me your chocolates plis
That's vietnamese, I am Vietnamese
I love rakai so much!
(Yo guys watch this, these 5 year olds will hate me in the comments)
Where's the extra annoying?
Dear Mr. Beast, I respectfully and humbly beg you to kindly consider assisting me with $200 to start my birds farm, as this small help would mean the world to me and my future.
Give me a computer that streamers have only played once. Give me one of these to throw around. This is my dream, I'm from Kyrgyzstan. ☺️☺️❤️🥲
@MrBeast My dream is to be a big YouTuber like you, but no one supports me. I'm not disappointed. Good luck to you going forward.♥️🥰
“MrBeast 👎
You’re missing out on 20 million views.
Before, when someone clicked your video, it would automatically play in the viewer’s local language based on their country. Now it doesn’t do that anymore. Because of this, a lot of people aren’t watching your videos.
It would be better if, as soon as someone clicks, the video plays in the language of the country they’re in so everyone can understand it easily.”
“MrBeast 👎
You’re missing out on 20 million views.
Before, when someone clicked your video, it would automatically play in the viewer’s local language based on their country. Now it doesn’t do that anymore. Because of this, a lot of people aren’t watching your videos.
It would be better if, as soon as someone clicks, the video plays in the language of the country they’re in so everyone can understand it easily.”
“MrBeast 👎
You’re missing out on 20 million views.
Before, when someone clicked your video, it would automatically play in the viewer’s local language based on their country. Now it doesn’t do that anymore. Because of this, a lot of people aren’t watching your videos.
It would be better if, as soon as someone clicks, the video plays in the language of the country they’re in so everyone can understand it easily.”
“MrBeast 👎
You’re missing out on 20 million views.
Before, when someone clicked your video, it would automatically play in the viewer’s local language based on their country. Now it doesn’t do that anymore. Because of this, a lot of people aren’t watching your videos.
It would be better if, as soon as someone clicks, the video plays in the language of the country they’re in so everyone can understand it easily.”
“MrBeast 👎
You’re missing out on 20 million views.
Before, when someone clicked your video, it would automatically play in the viewer’s local language based on their country. Now it doesn’t do that anymore. Because of this, a lot of people aren’t watching your videos.
It would be better if, as soon as someone clicks, the video plays in the language of the country they’re in so everyone can understand it easily.”
Sooooo, why isn't my king, Joseph Bartolozzi, there?
Mr.Beast what is your first second and third favorite animal and color? Favorite food and drink. I would like to draw you please
I unsubscribed to Mr beast cause clearly 8:16  she won cause she pulled her hand off exactly 10 and the boy did it in 9:58 so that isn’t equal Mr beast get canceled
why isn't twich rakai banned? Who's looking after him so much that they don't give him a ban, and if they do, they just take it away?
Letting  Rakai grab him ruined the entire competition. Jimmy should have made it right and eliminated him.
Dude I thought ski only made music, I didn’t know he streamed.
I dont know how many would agree to do it but this would be super cool with like the OGs of the platform. I know alot of them are done making content on YouTube but it would be a cool blast from the past, people like NigaHiga, Ray William Johnson, Jenna Marbles, Tyler Oakley etc. I remember when I startec watching YouTube NigaHiga was the most subscribed at like 7 Million. Would be cool to have them back and show them the path they have carved all them years ago.
Hi, I really love this content ❤️ I play Free Fire but I can’t afford diamonds. If anyone is willing to help, please reply to this comment. I would really appreciate it 🙏
We don't wanna see Rakai again, he's a really disgusting person
Everyone rage on Rakai who just had a strategy for a kid game and gave us entertainment
Seriously guys for those who were serious dont forget that it's a game. XD
Ratkai was doing to much in 45:12 because if that was him going home he would be mad and he just passed me off.
IShowSpeed it's awfull. I don't understand why you put him on the videos Beast. 😢
Rakai needs to be taught some manners.
"Dear MrBeast sir , I am writing this not just as a fan, but as a student from Myanmar whose future feels paused. Recently, my phone—my only tool for education and content creation—was stolen. In my country's current reality, a phone isn't a luxury; it's a lifeline for learning and survival. Psychologically, losing your only connection to the world feels like losing your voice. I have so many stories to tell and dreams to build as a creator, but I am now digitally silenced. I am not looking for a handout, but a hand up to continue my education and creative journey. A high-performance tool would change my entire life's trajectory. Thank you for being a beacon of hope for so many."
These challenges make no sense, they are mostly hidden, super RNG no skill, if they knew they were going to shoot a football, they would have all hopped in the BR
Hello team,
Mr beast i challenge you to
I'm the man your looking for
I can make anything 100 days if you invite me



Mr unknown
I don't use any social media
I don't know why Mr. Beast invites people like Ratkai.
I wonder how people felt having to deal with emily after she leaked them.  Especially tyler
If you guys hate him than why you people are not unsubscribing him he don't deserve to be famous kai cenet did a mistake but we have the right to correct that mistake so please unsubscribe him. We have the power to show his real place where he belongs so please unsubscribe because that toxic behavior is not acceptable
I also subscribed and watched your videos, and I wish you would give me something :((
Hello Mr. Best, can your subscribers do something like this so that I can get a surprise and become my only 10K subscriber?😮
Alway's choosing the youtubers who are already rich but nerver the one's who are lacking money.
Hi, I know you might not see this message, but I wanted to tell you that I really like your videos  , t’es le meilleur youtubeur au monde
Damn, props to Jasontheween for controlling his temper cuz Rakai oh my God, EVEN AT THE END.
Hi Mr. Beast Im Filipina watching your videos. I hope you have games or help for us here to help our family out. Thank you and God Bless
Can you make a video for kids may from ban on youtube there other accounts ban on youtube to and i got the same thing i'm saying right now but i'm in philippines😊😊
Can you make a video for kids may from ban on youtube there other accounts ban on youtube to and i got the same thing i'm saying right now but i'm in philippines
Can you make a video for kids may from ban on youtube there other accounts ban on youtube to and i got the same thing i'm saying right now but i'm in philippines
Sir, You are giving money to those who are rich. But I am earning just $400 per annum . So, I am unable to provide my child a good education. Please help me. I will be really thankful to you?
Hi, Jimmy! Try recording any new video while wearing a mask that completely covers Your face.
Hey MrBeast,

I saw your transformation video where you helped someone completely change their life, and it honestly inspired me.

I have a different dream.

My dream is basketball.

I would love to see what would happen if someone like you took a raw player with huge ambition and documented the journey of turning him into an elite basketball player over 6–12 months.

Not just a body transformation —
but a full basketball transformation.

The idea would be:
Can MrBeast help turn someone into a real basketball player?

I would give everything I have for that opportunity.

Thank you for reading this.
I've never seen someone I dislike so much in just a few seconds as Rakai.
I challenge you that i can stay 24 hours on the world silent room
@MrBeast please meet Khan sir at least once

He is doing very good work for poor children You should check it out once you’ll be happy
Please sir ❤
You, I am from Banjara, I am a very poor person, Mr. Beast.
@MrBeast give me sum money please
If there's lots of French people there
They got a Frenchship👻
Frenchship friendship
MrBeast fans, I’ve got a challenge for you 👀 Can you get this account to 20K followers in 24 hours? 🔥🚀
Your is  very good, but  is very basic
Hello I am a new subscriber, today you can help us in Haiti too that would be very nice 🙏
Whoever can support this girl,, please do so. She needs help as soon as possible. Her channel name is (براءة من غزة) (Bara'a from Gaza). This comment is not related to the content.
Hi Mrbeast, I've been subscribing to you for a long time. I want you to notice my comments. Can I ask you for one request?
Try staying at home for 24 hours without touching the ground.
Hey Mr Beast I am your biggest fan from Pakistan, my name is Abubakar and I really likes your videos, and watches your content sincerly when you started you channel, and I am so happy with you that you meet Zalmi, and I also speak pashto as like zalmi, and I request you to come to Pakistan because 100k likes and 5m views were completed on that Zalmi brother video when he collabs with you, and if you come to our country everyone will be welcoming you, and we will be showing you many of the places like swat,kashmir,islamabad,karachi,lahore,gilgit, and many of the peacful and historical places and temples, and even you went to india but did not come to pakistan, everyone in pakistan knows you and watches your videos, and even the likes and views were not completed on carryminati's video but you came.

We will see you in pakistan and welcoming you from the airport Inshallah and if you will be coming so come with your members chandler,carl,nolan, and tareq, see you as a guest in Pakistan.
It's amazing how they can consistently create projects that everyone finds interesting
They poured millions of dollars into it, and Rakai screwed it all up.
38:38 I'm a Malaysian watching your movie, I like it.
@mrBeast don't invite Ratkai anymore, that guy went too far
Mr beast can you make festiblse in jamaica  island all of it.
I can't help but hate almost all of them. But mostly xqc, I don't know how anyone can tolerate him.
Hello Mr. Best, I also want to join one of your games.
Day 1 of finding someone with the same name as me on a random youtube comment.
All of these streamers couldn't have walked without Ice Poseidon.
Thanks for the content, very helpful.
I want to talk to you @MrBeast
Hello, I am Vietnamese. Have a great day!
Can you pls not appear in ads?
"Get Rakai out of the game, Jimmy. Everyone can see what you're doing. Rakai has a bad personality and is a shameless cheater."
Dear sir I am in big financial trouble I have asked for help from everyone I can ask for help and no one has helped me if you can help me humanly please kindly respond to this message....🥺💔
36:19 yah bai, it’s not worth watching to the end after mari leaving. ✌🏻 @msgmarigaming
Hello, on June 3rd, the word “freedom” will disappear from the Constitution of the Republic of Korea. We are heading toward communism, totalitarianism, and socialism.
It is also being said that 100 million Chinese citizens will be granted visa-free entry to Korea for 10 years. It feels as though the country could be handed over without a single shot being fired.
I hope that major YouTubers like MrBeast will help spread the word so that people around the world who love Korea can support us. I sincerely ask for your help.
As a citizen of South Korea, it is unfortunate that this is all I can do. I would truly appreciate it if you could share this message widely.
What about Extra Emily ruining everything?
Brother, we are very poor, if you help us a little, our life can change. Please Mr Beast
Watching you since I was a kid has been my biggest inspiration. My dream is to one day fly out and compete in one of your legendary challenges! Much love from the Arab world! ❤️"
Is ishowspeed here i. The contest
God bless you for giving money to the poor people and building water wells in Africa. ☦️
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺🙏🙏🙏🙏🙏
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺🙏🙏🙏🙏
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺😅😅😅😅😅
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺😢😢😢😢😢
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺🙏🙏🙏🙏🙏
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺😢
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺😅
Mr.Beast  Please help me with 8 million dollars. 🥺🥺🥺🥺
Hello MrBeast,
I am Jisan, a student from India. I have a dream to build a school with classrooms, a computer center, gym, playground, dormitories, and buses for students.

I truly admire your work and how you help people. Even a little support or guidance from you could help change many lives.

Thank you so much 🙏
I can't sleep without watching beast videos.
Do you want to play brawl stars with me?
Hi! Could you try playing Brawl Stars? It would be really fun to watch!
Hey Mr. Beast, let's play Brawl Stars? Please, or at least reply to my comment. It would be a birthday present for me pleaseee I love your videos😄
Can you play Brawl Stars in a video?
Mr. Beast, do you really give money? I'm your fan
Hi, let's go play brawl stars together.
I'm Indonesian, but I see no Indonesians have joined your challenge yet. Can I join? I really hope so🫵
How do you like the idea of ​​playing Brawl Stars with me?
Mr beast I hope you learn from your comments and never have rakai on one of these ever again he might be one of the most annoying streamers on planet earth I mean MILLIONS many even BILLIONS of people hate him
Mr. Beast, can you make seaweed and sell it like chocolate?
You should do a challenge on food
Eliminating Rakai is the most satisfying in this video.
“Dear MrBeast,
I’m begging you from the bottom of my heart—please help me with $1000. I am going through an extremely difficult time in my life, and I feel completely helpless. Every day is a struggle, and I don’t see a way out anymore.

In [ ]:
np.bincount(preds)

array([867, 180])

Looking at the results, a lot of them seems AI generated or at least they seem like people used AI to refine their posts.